<div class="space-y-6">
    <div>
        <h1 class="text-3xl font-bold tracking-tight text-slate-900">
            Import SPT Lama
        </h1>
        <p class="mt-1 text-sm text-slate-500">
            Masukkan arsip SPT lama tanpa harus membuat ulang surat melalui template.
        </p> 
        <p class="mt-2 text-xs text-blue-700">
            Nilai personil ALL PEGAWAI, SEMUA PEGAWAI, atau SELURUH PEGAWAI
            akan disimpan sebagai cakupan seluruh pegawai dan tidak dibuat
            sebagai data personil.
        </p>
    </div>

    <div class="grid grid-cols-4 gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">@foreach([1=>'Upload File',2=>'Mapping Kolom',3=>'Preview',4=>'Selesai'] as $number=>$label)<div class="rounded-xl px-3 py-3 text-center text-sm font-semibold {{ $step >= $number ? 'bg-blue-600 text-white' : 'bg-slate-50 text-slate-400' }}">{{ $number }}. {{ $label }}</div>@endforeach</div>
    <p class="mt-2 text-xs text-blue-700">
        Nilai personil ALL PEGAWAI, SEMUA PEGAWAI, atau SELURUH PEGAWAI
        akan disimpan sebagai cakupan seluruh pegawai dan tidak dibuat
        sebagai data personil.
    </p>

    @if($step === 1)
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-10 text-center"><div class="mx-auto mb-4 flex size-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><svg class="size-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v12M7 8l5-5 5 5"/><path d="M5 21h14a2 2 0 0 0 2-2v-4"/></svg></div><h2 class="text-lg font-bold">Upload file arsip SPT</h2><p class="mt-1 text-sm text-slate-500">Format didukung: CSV dan XLSX, maksimal 10 MB.</p><input type="file" wire:model="file" accept=".csv,.xlsx" class="mx-auto mt-5 block max-w-sm text-sm">@error('file')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror<div class="mt-6"><button wire:click="readFile" wire:loading.attr="disabled" class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Baca File</button></div></div></div>
    @elseif($step === 2)
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="mb-5"><h2 class="text-lg font-bold">Mapping Kolom</h2><p class="text-sm text-slate-500">Cocokkan kolom file lama dengan field sistem. Nomor SPT wajib dipetakan. Kolom Jenis Record dapat berisi <strong>normal</strong> atau <strong>koreksi absensi</strong>.</p></div><div class="grid gap-4 md:grid-cols-2">@foreach(['number'=>'Nomor SPT *','letter_date'=>'Tanggal SPT','start_date'=>'Tanggal Mulai','end_date'=>'Tanggal Selesai','subject'=>'Perihal','activity'=>'Jenis Kegiatan','location'=>'Lokasi','personnel_names'=>'Nama Personil','personnel_nips'=>'NIP Personil','description'=>'Keterangan','record_type'=>'Jenis Record'] as $field=>$label)<label class="space-y-1"><span class="text-sm font-semibold text-slate-700">{{ $label }}</span><select wire:model="mapping.{{ $field }}" class="w-full rounded-xl border-slate-200 text-sm"><option value="">-- Tidak dipetakan --</option>@foreach($headers as $header)<option value="{{ $header }}">{{ $header }}</option>@endforeach</select></label>@endforeach</div>@error('mapping.number')<p class="mt-3 text-sm text-red-600">{{ $message }}</p>@enderror<div class="mt-6 flex justify-end"><button wire:click="goPreview" class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Lanjut Preview</button></div></div>
    @elseif($step === 3)
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-lg font-bold">Preview Data</h2><p class="text-sm text-slate-500">Menampilkan 10 baris pertama dari {{ count($rows) }} baris.</p></div><button wire:click="$set('step', 2)" class="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Ubah Mapping</button></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>@foreach($headers as $header)<th class="whitespace-nowrap px-3 py-3">{{ $header }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@foreach($previewRows as $row)<tr>@foreach($headers as $header)<td class="max-w-52 truncate px-3 py-3">{{ $row[$header] ?? '' }}</td>@endforeach</tr>@endforeach</tbody></table></div><div class="mt-6 flex justify-end"><button wire:click="import" wire:confirm="Import data SPT lama sekarang? Data yang sudah masuk akan tercatat sebagai Import Arsip." class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Import {{ count($rows) }} Baris</button></div></div>
    @elseif($step === 4 && $lastBatch)
        <div class="rounded-2xl border border-emerald-200 bg-white p-8 shadow-sm"><div class="mx-auto max-w-2xl text-center"><div class="mx-auto flex size-16 items-center justify-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h2 class="mt-4 text-2xl font-bold">Import selesai</h2><p class="mt-2 text-sm text-slate-500">Batch #{{ $lastBatch->id }} · {{ $lastBatch->original_filename }}</p><div class="mt-6 grid gap-3 sm:grid-cols-4"><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">Total</p><p class="text-2xl font-bold">{{ $lastBatch->total_rows }}</p></div><div class="rounded-xl bg-emerald-50 p-4"><p class="text-xs text-emerald-700">Diimport</p><p class="text-2xl font-bold text-emerald-700">{{ $lastBatch->imported_rows }}</p></div><div class="rounded-xl bg-amber-50 p-4"><p class="text-xs text-amber-700">Duplikat</p><p class="text-2xl font-bold text-amber-700">{{ $lastBatch->summary['duplicates'] ?? 0 }}</p></div><div class="rounded-xl bg-red-50 p-4"><p class="text-xs text-red-700">Gagal</p><p class="text-2xl font-bold text-red-700">{{ $lastBatch->failed_rows }}</p></div></div><div class="mt-6 flex justify-center gap-3"><button wire:click="restart" class="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-semibold">Import Lagi</button><a href="{{ route('spt-recap.index') }}" wire:navigate class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Lihat Rekap SPT</a></div></div></div>
    @endif

    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Riwayat Import Terbaru</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">File</th><th class="px-4 py-3">Waktu</th><th class="px-4 py-3">Oleh</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Diimport</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($recentBatches as $batch)<tr><td class="px-4 py-3 font-medium">{{ $batch->original_filename }}</td><td class="px-4 py-3">{{ $batch->created_at?->translatedFormat('d M Y H:i') }}</td><td class="px-4 py-3">{{ $batch->uploader?->name ?: '-' }}</td><td class="px-4 py-3">{{ $batch->total_rows }}</td><td class="px-4 py-3">{{ $batch->imported_rows }}</td><td class="px-4 py-3"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{{ $batch->status }}</span></td></tr>@empty<tr><td colspan="6" class="px-6 py-10 text-center text-slate-500">Belum ada riwayat import.</td></tr>@endforelse</tbody></table></div></div>
</div>
